### ISSUE TITLE
GATK workflow README references Trello board which is either private or gone

### ISSUE THREAD

**Issue by tfmorris** [common-workflow-language/workflows#131]
The README references the following which isn't accessible:

https://trello.com/b/pcWKqbXv/stream-b-ngs-variant-calling-illumina

**Comment by mr-c** [comment]
Hello @tfmorris -- thank you for your sharp eye.

That [README](https://github.com/common-workflow-language/workflows/blob/154c80e16d71ea32471ad2a4e5f1a605ac34273f/workflows/GATK/README.md)
 hasn't been merged yet -- why don't you leave your comment over at the open Pull Request? 

https://github.com/common-workflow-language/workflows/pull/119
