### ISSUE TITLE
Did you include a $schemas section?

### ISSUE THREAD

**Issue by evan-wehi** [common-workflow-language/workflows#137]
Hello,

I'm building a workflow and using CommandLineTool examples from this repository (which are great!). Many have metadata but including them in a workflow produces:

```
$ ../src/pdx-pl.cwl pdx-inp.yml 
/home/thomas.e/.local/bin/cwl-runner 1.0.20170622090721
Resolved '../src/pdx-pl.cwl' to 'file:///stornext/Home/data/allstaff/t/thomas.e/dev/pdx-genome/src/pdx-pl.cwl'
No handlers could be found for logger "rdflib.term"
../src/tools/samtools-sort.cwl:66:1: unrecognized extension field `s:downloadUrl`.  Did you include a $schemas section?
../src/tools/samtools-sort.cwl:68:1: unrecognized extension field `s:license`.  Did you include a $schemas section?
../src/tools/samtools-sort.cwl:75:1: unrecognized extension field `s:author`.  Did you include a $schemas section?
```

This example uses the `samtools-sort.cwl` directly from the repository (other than commenting out the imports for `envvar-global.ylm` and `samtools-docker.yml`)

**Comment by michael-kotliar** [comment]
It's not the best solution, but you may try to run it with --non-strict flag. It will allow to ignore these warnings

**Comment by mr-c** [comment]
Hello @evan-wehi 

Thank you for reporting your issue. This is a regression in `cwltool` -- I thought we had documented it already, but evidently not. I'm moving the issue to https://github.com/common-workflow-language/cwltool/issues/455

**Comment by evan-wehi** [comment]
Thanks for looking at it @mr-c

Evan.
