### ISSUE TITLE
gatk_germline.png change trimmamatic to trimmomatic

### ISSUE THREAD

**Issue by raonyguimaraes** [common-workflow-language/workflows#144]
It's actually trimmomatic instead of trimmamatic.

Can someone please correct the image @briandoconnor ?

**Comment by mr-c** [comment]
@raonyguimaraes I think you are looking for a different repository, perhaps  https://github.com/h3abionet/h3agatk/issues ?

**Comment by raonyguimaraes** [comment]
Thanks @mr-c
