### ISSUE TITLE
lobSTR example fails: node-engine.cwl is a link to nothing

### ISSUE THREAD

**Issue by prismofeverything** [common-workflow-language/workflows#62]
Hi,

Trying to run the lobSTR example, I discover that `node-engine.cwl` is a link to a file `/engines/node-engine.cwl`. However, this file does not exist in the repository, and causes the example to blow up.

Is this a directory someone has locally they have not checked in to the repository?

**Comment by mr-c** [comment]
Thank you Ryan for reporting this issue. The lobSTR example needs updating
to the Draft 3 version of CWL as the way JavaScript works changed.
Pe 16 mar. 2016 18:25, "Ryan Spangler" <notifications@github.com> a scris:

**Comment by tdanford** [comment]
@mr-c any pointers or high level descriptions, as to what would need to be changed to fix this?  I ran into it today too, would be happy to help if there's something I can do.

**Comment by mr-c** [comment]
@tdanford Pardon my lack of response. I have this almost finished in https://github.com/common-workflow-language/workflows/pull/70

However the `docker load` command is failing:
```
Error response from daemon: invalid argument
Workflow error:
  Docker load returned non-zero exit status 1
```
I'm running Docker version 1.10.3, build 20f81dd
Perhaps @tetron or @portah know what's going on here.

**Comment by mr-c** [comment]
@tdanford Okay, I just learned that the docker issue I had is because Docker changed the on-disk format in 1.10. I'll update the Readme to reflect that. Otherwise this appears to be working now.
