### ISSUE TITLE
Typo in hello

### ISSUE THREAD

**Issue by SamGG** [common-workflow-language/workflows#72]
At line 55 https://github.com/common-workflow-language/workflows/blob/master/workflows/hello/hello-param.cwl#L55, there seems to be a missing t to defaul**t**.

**Comment by mr-c** [comment]
Hello @SamGG thank you for pointing this out!

This has been subsequently fixed by https://github.com/common-workflow-language/workflows/commit/87195224c932d63bfa1ec928f25ecdfafb1337d7

Cheers
