### ISSUE TITLE
Travis check fail

### ISSUE THREAD

**Issue by anton-khodak** [common-workflow-language/workflows#96]
I have confronted with the following error during Travis build
https://travis-ci.org/common-workflow-language/workflows/builds/146887725

    $ docker pull commonworkflowlanguage/nodejs-engine
    Using default tag: latest
    Pulling repository docker.io/commonworkflowlanguage/nodejs-engine
    Error: image commonworkflowlanguage/nodejs-engine:latest not found
    The command "docker pull commonworkflowlanguage/nodejs-engine" failed and exited with 1 during .

seems like the error is internal, in the previous builds this step succeeded

    $ docker pull commonworkflowlanguage/nodejs-engine
    Using default tag: latest
    latest: Pulling from commonworkflowlanguage/nodejs-engine
    Status: Downloaded newer image for commonworkflowlanguage/nodejs-engine:latest

**Comment by mr-c** [comment]
Thank you @anton-khodak for your report. That docker image doesn't exist anymore and for good reason. I've removed it from the `.travis.yml` and restarted the test for your branch.

**Comment by anton-khodak** [comment]
Another issue occured with tools which already passed tests before

    Testing: alea-alignReads
    Test [1/1] No handlers could be found for logger "rdflib.term"
    Workflow error, try again with --debug for more information:
      Document has DockerRequirement under 'requirements' but use_container is false. DockerRequirement must be under 'hints' or use_container must be true.
    Test failed: cwltool --conformance-test --basedir=. --no-container --quiet ../tools/alea-alignReads.cwl alea-alignReads-job.json
